### ISSUE TITLE
Shopify API: Update to a supported version

### ISSUE THREAD

**Issue by evannoronha** [iFixit/shopify-analytics#5]
### Problem

![image](https://user-images.githubusercontent.com/6803522/147890767-66bdb864-313d-426a-b83f-2be695d9f1d5.png)

https://airflow.ifixit.com/admin/airflow/log?execution_date=2022-01-02T21%3A30%3A00%2B00%3A00&task_id=shopify-analytics-ca&dag_id=shopify-analytics-ca

Log failures look like:

```
[2022-01-02 21:45:47,414] {pod_launcher.py:156} INFO - b'Traceback (most recent call last):\n'
[2022-01-02 21:45:47,414] {pod_launcher.py:156} INFO - b'  File "/opt/shopify-analytics/get_orders.py", line 59, in <module>\n'
[2022-01-02 21:45:47,414] {pod_launcher.py:156} INFO - b'    session = shopify.Session(shop_url, "2021-01", os.environ[\'SHOPIFY_PASSWORD\'])\n'
[2022-01-02 21:45:47,414] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.9/site-packages/shopify/session.py", line 47, in __init__\n'
[2022-01-02 21:45:47,414] {pod_launcher.py:156} INFO - b'    self.version = ApiVersion.coerce_to_version(version)\n'
[2022-01-02 21:45:47,414] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.9/site-packages/shopify/api_version.py", line 19, in coerce_to_version\n'
[2022-01-02 21:45:47,414] {pod_launcher.py:156} INFO - b'    raise VersionNotFoundError\n'
[2022-01-02 21:45:47,414] {pod_launcher.py:156} INFO - b'shopify.api_version.VersionNotFoundError\n'
```

Here's the important bit:

`shopify.api_version.VersionNotFoundError`

Here's where we specify the API version:

https://github.com/iFixit/shopify-analytics/blob/48284ff6b615087f0d6fa7bbc13ccfb706d701c8/get_orders.py#L59

[And as of January 1 2022, that is unsupported:
](https://shopify.dev/api/usage/versioning#release-schedule)

![image](https://user-images.githubusercontent.com/6803522/147890799-930a5ace-f9b6-440c-97c7-6eedfa91cdd6.png)

**Comment by evannoronha** [comment]
Closed in https://github.com/iFixit/shopify-analytics/pull/6
